# Generated by Django 3.1.4 on 2020-12-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
