# Generated by Django 3.1.4 on 2020-12-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201212_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
