# Generated by Django 3.1.4 on 2020-12-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201212_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True False'), ('FOTB', 'Fill in the Blank'), ('D', 'Dropdown')], max_length=10),
        ),
    ]
