# Generated by Django 3.1.4 on 2020-12-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201210_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default=0, max_length=250),
        ),
    ]
