# Generated by Django 3.1.4 on 2020-12-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201213_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveuserinstance',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True False'), ('T', 'Type Answer'), ('D', 'Dropdown')], max_length=10),
        ),
    ]
