# Generated by Django 3.1.6 on 2021-02-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201216_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='playId',
            field=models.CharField(default=0, editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
