# Generated by Django 3.1.6 on 2021-02-11 01:29

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_playid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='playId',
            field=models.CharField(default=quiz.models.key_generator, editable=False, max_length=6),
        ),
    ]
